name: update-theme-on-server

on: 
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Pull theme
    runs-on: ubuntu-latest
    steps:
    - name: Pull from master
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          whoami
          cd ~/bcb-docker/wp-content/themes/NeoBCB21
          git pull origin master
