name: update-theme-on-staging

on:
  push:
    branches:
      - bcb-2023

jobs:
  build:
    name: Pull theme
    runs-on: ubuntu-latest
    steps:
    - name: Pull from staging branch
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/bcb-docker/staging-wp-content/themes/bcb-theme
          git pull
    - name: Discord notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}

